---
title: "Analysis"
author: "Huy Le Quang"
date: "7/15/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F)
```

## 1.Introduction

## 2. Dataset

## 3. Descriptive analysis

xxx

```{r, warning=FALSE}

# Load necessary packages

library(tidyverse)
library(sparklyr)
library(lubridate)

```

xxx

```{r, warning=FALSE}

# Download data

lookup.table.url <- "https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv?raw=true"

lookup.table <- read.csv(url(lookup.table.url))


time.series.url <- "https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv?raw=true"
time.series <- read.csv(url(time.series.url))

```
xxx

```{r, warning=FALSE}

# Clean the time series dataset

time.series <- time.series[-c(3, 4)] # delete unnecessary columns

names(time.series)[names(time.series) == 'Country.Region'] <- 'country'
names(time.series)[names(time.series) == 'Province.State'] <- 'state'

time.series.long <- pivot_longer(data = time.series,
                          -c(state, country),
                          names_to = "date") # reshape to long format

# Change to date format
time.series.long$date <- as.Date(gsub("X", "", time.series.long$date), "%m.%d.%y") 

begin.date <- as.Date("2020-01-22")

# Calculate the number of days since the start of data collection

time.series.long <- time.series.long %>% 
    mutate(day_difference = date - begin.date)

# Change variable names in lookup dataset

names(lookup.table)[names(lookup.table) == 'Country_Region'] <- 'country'
names(lookup.table)[names(lookup.table) == 'Province_State'] <- 'state'

```

## Establish Spark server and copy two datasets to this server

```{r, warning=FALSE}

# Connect to local Spark server

sc <- spark_connect(master = "local", 
                    version = "2.3")

# Copy two datasets to Spark server

time.series.long <- copy_to(sc, time.series.long, overwrite = T)
lookup.table <- copy_to(sc, lookup.table, overwrite = T)

# Merge two datasets

data_long <- full_join(time.series.long, lookup.table, by = c("state","country"))

# Rename variables

data_long <- data_long %>% 
    rename(latitude = Lat,
           longitude = Long_,
           population = Population,
           country_code = iso3,
           confirmed_cases = value)

# Make a smaller dataset and generate two new variables

data_final <- data_long %>% 
    filter(country == "Germany"|country == "China"|country == "Japan"|
            country == "United Kingdom"|country == "US"|
            country =="Brazil"|country == "Mexico")%>%
    mutate(log.confirmed_cases = log((confirmed_cases+1)),
           infection_rate = confirmed_cases/population*100000)


```

## Including Plots

```{r, warning=FALSE}

## Overall change in time of log number of cases

ggplot(aes(x = date, y = log.confirmed_cases),
       data = data_final) +
    stat_summary(fun.y = mean,
                 geom = "line") + 
    theme_bw() +
    facet_wrap(~country) +
    labs(x = "Date", y = "Log number of cases",
         title = "Overall change in time of log number of cases by country",
         caption = "Data: JHU CSSE COVID-19 Dataset")

# Infection rate

ggplot(aes(x = date, y = infection_rate),
       data = data_final) +
    stat_summary(fun.y = mean,
                 geom = "line") +
    facet_wrap(~country) +
    scale_y_continuous(labels = scales::number_format(accuracy = 1)) +
    theme_bw() +
    labs(x = "Date", y = "Infection rate (per 100,000 people)",
         title = "Change in time of infection rate by country",
         caption = "Data: JHU CSSE COVID-19 Dataset. Infection rate per 100,000 people")

```

# Regression model

```{r}

data_final %>% lm(formula = log.confirmed_cases ~ country + population + day_difference) %>% 
summary()

```

